App\Entity\Shelf:
  type: entity
  repositoryClass: App\Repository\ShelfRepository
  table: shelf
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    shelfIdentifier:
      type: string
      column: shelf_identifier
    floor:
      type: integer
      nullable: false
  oneToMany:
    books:
      targetEntity: Book
      mappedBy: shelf